### ISSUE TITLE
Cannot build site in Linux

### ISSUE THREAD

**Issue by alpeb** [linkerd/website#119]
```
$ make publish DRY_RUN=true
mkdir -p tmp
cp -R *linkerd.io tmp/
for fname in $(grep -rnl 'L5D2_STABLE_VERSION' tmp); do \
        sed -i '' 's/L5D2_STABLE_VERSION/stable-2.1.0/g' $fname; \
done
sed: can't read s/L5D2_STABLE_VERSION/stable-2.1.0/g: No such file or directory
sed: can't read s/L5D2_STABLE_VERSION/stable-2.1.0/g: No such file or directory
sed: can't read s/L5D2_STABLE_VERSION/stable-2.1.0/g: No such file or directory
make: *** [Makefile:85: replace-env-L5D2_STABLE_VERSION] Error 2
```

**Comment by klingerf** [comment]
I think the issue is different versions of sed. On darwin, to edit-in-place, you pass `-i ''`, but I'm pretty sure `-i` doesn't take an argument on linux. We could switch to not editing in place. Lonnng stack overflow post about this here: https://stackoverflow.com/questions/5694228/sed-in-place-flag-that-works-both-on-mac-bsd-and-linux

**Comment by alpeb** [comment]
@klingerf thanks for the tip :slightly_smiling_face: 
I've pushed a PR addressing this.
