### ISSUE TITLE
Add more information around the --ha flag

### ISSUE THREAD

**Issue by jonrichards** [linkerd/website#400]
With [https://github.com/linkerd/linkerd2/issues/2419](https://github.com/linkerd/linkerd2/issues/2419) now closed, and [https://github.com/linkerd/linkerd2/issues/1895](https://github.com/linkerd/linkerd2/issues/1895) still in progress, the [High Availability](https://linkerd.io/2/features/ha/) documentation should have expanded details on what `--ha` does, and does not do.

For example:
- Which components get increased resource requests?
- Which components are setup with replicas?
- Which ones have anti-affinity set?

A use case I have in mind as I consider "high availability" is in a single cluster node failure scenario, what would the potential impact to Linkerd2 be (e.g. control plane is down temporarily, new pod injection is down, etc...)?

**Comment by cmur2** [comment]
I just discovered that contrary to what https://github.com/linkerd/website/blame/master/linkerd.io/content/2/features/ha.md#L18 states some anti-affinity settings are already in place since the 2.5.0 release (https://github.com/linkerd/website/blob/master/linkerd.io/content/blog/announcing-linkerd-2-5.md). This update should be reflected in the documentation to not confuse readers.

**Comment by wmorgan** [comment]
Thanks for catching this @cmur2. Would you like the fame and glory of submitting a PR to fix this?

**Comment by cmur2** [comment]
@wmorgan I did and hope you could maybe have a look at https://github.com/linkerd/website/pull/508 since I'm a bit unsure if the information and style provided suits you.

**Comment by ihcsim** [comment]
Fixed by #508.
