### ISSUE TITLE
Namespace access control

### ISSUE THREAD

**Issue by mooperd** [linkerd/website#702]
On the website is the statement "By default, the Secret is placed in the linkerd namespace and can only be read by the service account used by the Linkerd control plane‘s identity component."

Kubernetes does not have any kind of "Deny" rules within its RBAC system - this statement would appear to be a bit misleading because any "standard" user on K8s would be able to read these secrets. This statement seems to be painting a picture that K8s has a granular deny/allow permissions system. It really really doesn't!

https://linkerd.io/2/features/automatic-mtls/

**Comment by grampelberg** [comment]
Hmm, do all your users have ClusterAdmin?

**Comment by mooperd** [comment]
Doing any kind of real user access control on kubernetes is a joke. 

My understanding at the moment is - unless you create every namespace with some special label and limit a users scope to a label - yes, all users will be defacto cluster-admins because there is no deny rules. Normally I am not allowing human users access to clusters because it's so difficult to implement. Everything happens via CI/CD.

I really think the statement on the website is somewhat misleading and not really achievable using the K8s RBAC system. People might assume that such fine grained RBAC was possible - when it really isn't

**Comment by grampelberg** [comment]
K8s RBAC is allow-only and unless you've granted users ClusterAdmin (which I would *very strongly* discourage), users are limited to namespaces they've been granted access to. Because RBAC is additive, by default the Linkerd namespace will not be visible to users.

FWIW, that comment is much more about service accounts than users as well. If you're granting global access to service accounts so they can read secrets, you've got a pretty large security issue in your cluster.

**Comment by mooperd** [comment]
meh - ok. I still think you're alluding to features that don't really exist in k8s but thats probably enough pedantry for now.
